"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta
from kombu import Queue
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 从 .env 读取环境变量（开发/测试/生产统一入口）
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY environment variable is required')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'false').lower() in ('true', '1', 'yes')

 # 允许访问的主机列表（生产环境务必配置为你的域名/IP），多个以逗号分隔
 # 例如：ALLOWED_HOSTS=example.com,api.example.com
 # 允许访问的主机列表（生产环境务必配置为你的域名/IP），多个以逗号分隔
 # 例如：ALLOWED_HOSTS=example.com,api.example.com
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]


# Application definition
# 应用注册清单：分为 Django 内置、第三方、自定义三类；删除未使用的以降低开销
INSTALLED_APPS = [
     # Django 内置应用
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 第三方应用
    'rest_framework',
    'drf_spectacular',
    'drf_spectacular_sidecar',
    'django.contrib.postgres',
    'corsheaders',

    # 自定义应用（使用新的路径）
    'apps.users',
    'apps.videos',
    'apps.interactions.apps.InteractionsConfig',
    'apps.content',
    'apps.recommendation',
    'apps.notifications',
    'apps.analytics',
    'apps.adminapi',
    'apps.configs',
    'apps.core.apps.CoreConfig',
    'apps.tasks',
]

# 中间件：执行顺序很重要。CORS 应位于 CommonMiddleware 之前，认证类要在 CSRF 之后
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 允许跨域的前端来源（Vue/管理端/移动端本地开发）。生产请收紧。
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:8080',
    'http://localhost:8081',
    'http://mobile.bs01.local:8081',
    'http://127.0.0.1:8080',
    'http://127.0.0.1:8081',
    'http://localhost:8082',
    'http://127.0.0.1:8082',
    'http://localhost:8090',
    'http://127.0.0.1:8090',
    'http://192.168.183.131:8080',
    'http://192.168.183.131:5173',
    'http://mobile.bs01.local:5173',
]
# allow override via env (comma-separated)
if os.getenv('CORS_ALLOWED_ORIGINS'):
    CORS_ALLOWED_ORIGINS = [h.strip() for h in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if h.strip()]
# 允许设置 CSRF 信任来源（启用 Cookie/Session 等跨站请求时需要）
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://mobile.bs01.local:5173',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    'http://localhost:8082',
    'http://127.0.0.1:8082',
    'http://localhost:8090',
    'http://127.0.0.1:8090',
]
if os.getenv('CSRF_TRUSTED_ORIGINS'):
    CSRF_TRUSTED_ORIGINS = [h.strip() for h in os.getenv('CSRF_TRUSTED_ORIGINS', '').split(',') if h.strip()]
CORS_ALLOW_CREDENTIALS = os.getenv('CORS_ALLOW_CREDENTIALS', 'true').lower() in ('true', '1', 'yes')

# URL 根路由配置，指向项目 urls.py
ROOT_URLCONF = 'backend.urls'

# 模板引擎配置：APP_DIRS=True 将自动在各 app 的 templates 目录中查找模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI 应用入口（Gunicorn/uWSGI 部署使用）
WSGI_APPLICATION = 'backend.wsgi.application'

 # Django REST framework 配置
REST_FRAMEWORK = {
    # 默认鉴权方式：优先使用 JWT，其次保留 Session 便于管理后台及开发调试
    'DEFAULT_AUTHENTICATION_CLASSES': (
        ['backend.auth.JWTAuthenticationWithRevoke', 'rest_framework.authentication.SessionAuthentication']
        if os.getenv('API_ENABLE_SESSION_AUTH', 'false').lower() in ('true', '1', 'yes')
        else ['backend.auth.JWTAuthenticationWithRevoke']
    ),
    # 默认权限：需登录（持有有效 JWT 或 Session）
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 分页配置
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'register': os.getenv('THROTTLE_REGISTER', '5/hour'),
        'verify_email': os.getenv('THROTTLE_VERIFY_EMAIL', '5/hour'),
        'password_reset': os.getenv('THROTTLE_PASSWORD_RESET', '5/hour'),
        'avatar_upload': os.getenv('THROTTLE_AVATAR_UPLOAD', '20/hour'),
        'login_code': os.getenv('THROTTLE_LOGIN_CODE', '30/hour'),
        'login_password': os.getenv('THROTTLE_LOGIN_PASSWORD', '60/hour'),
        # 保留旧的扫码登录节流键，兼容尚未切换到细粒度 scope 的视图
        'qr_login': os.getenv('THROTTLE_QR_LOGIN', '600/hour'),
        'qr_login_create': os.getenv('THROTTLE_QR_LOGIN_CREATE', '120/hour'),
        'qr_login_status': os.getenv('THROTTLE_QR_LOGIN_STATUS', '3600/hour'),
        'qr_login_confirm': os.getenv('THROTTLE_QR_LOGIN_CONFIRM', '600/hour'),
        'follow': os.getenv('THROTTLE_FOLLOW', '200/hour'),
        'comments': os.getenv('THROTTLE_COMMENTS', '120/hour'),
        # 观看历史上报（播放器每 10s 一次，实际会去抖；按小时限速足够）
        'history': os.getenv('THROTTLE_HISTORY', '3600/hour'),
        'video_upload': os.getenv('THROTTLE_VIDEO_UPLOAD', '20/hour'),
        'analytics': os.getenv('THROTTLE_ANALYTICS', '5000/hour'),
        'recommendation_feed': os.getenv('THROTTLE_RECOMMENDATION_FEED', '1800/hour'),
        'following_feed': os.getenv('THROTTLE_FOLLOWING_FEED', '1800/hour'),
        'featured_feed': os.getenv('THROTTLE_FEATURED_FEED', '1800/hour'),
        # 用户头像弹窗汇总接口节流（避免滥刷）。需与视图中的 throttle_scope=popup_stats 对应。
        'popup_stats': os.getenv('THROTTLE_POPUP_STATS', '1800/hour'),
        # 联系我们表单提交
        'contact_submit': os.getenv('THROTTLE_CONTACT_SUBMIT', '30/hour'),
        'anon': os.getenv('THROTTLE_ANON', '100/hour'),
        'user': os.getenv('THROTTLE_USER', '1000/hour'),
    },
    # 统一异常处理（错误返回结构统一）
    'EXCEPTION_HANDLER': 'backend.api_exceptions.custom_exception_handler',
    # OpenAPI schema generation
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'BS01 API',
    'DESCRIPTION': 'BS01 后端业务接口文档',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'SIDECAR',
    'SWAGGER_UI_FAVICON_HREF': 'SIDECAR',
    'REDOC_DIST': 'SIDECAR',
}

# 自定义用户模型
AUTH_USER_MODEL = 'users.User'

# SimpleJWT 配置：令牌有效期、前缀等
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(os.getenv('REFRESH_TOKEN_LIFETIME_DAYS', '60'))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),  # 客户端请求头格式：Authorization: Bearer <token>
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 默认使用 PostgreSQL（推荐用于生产），所有连接参数从 .env 读取：
# - DB_NAME：数据库名
# - DB_USER：数据库用户
# - DB_PASSWORD：数据库密码
# - DB_HOST：数据库主机（本机可用 127.0.0.1，或留空使用本地套接字）
# - DB_PORT：端口（PostgreSQL 默认 5432）
# 如需本地轻量调试，也可将 DB_ENGINE 临时改为 SQLite：django.db.backends.sqlite3
DB_ENGINE = os.getenv('DB_ENGINE', 'django.db.backends.postgresql')
if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
            # 长连接（秒）。0 表示禁用连接复用；生产环境可设置 60~300 提升性能
            'CONN_MAX_AGE': int(os.getenv('DB_CONN_MAX_AGE', '60')),
            # 每个请求使用原子事务（严格一致性需求可改为 True）
            'ATOMIC_REQUESTS': False,
            # 测试库名称（Django 默认创建 test_<DB_NAME>；也可通过 DB_TEST_NAME 指定）
            'TEST': {
                'NAME': os.getenv('DB_TEST_NAME', f"test_{os.getenv('DB_NAME', '')}"),
            },
            # 如需强制 SSL 连接可启用下行配置
            # 'OPTIONS': {'sslmode': 'require'},
        }
    }

# 测试运行也使用 PostgreSQL，仅保留测试加速项（更快的密码哈希器）
if 'test' in sys.argv:
    # 加速测试（更快的密码哈希器）
    PASSWORD_HASHERS = [
        'django.contrib.auth.hashers.MD5PasswordHasher',
    ]


# 密码强度校验（生产建议保持开启）
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# 国际化与本地化
# 使用简体中文与上海时区；USE_TZ=True 表示以 UTC 存储，按时区展示
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
# 生产环境通常由 Nginx/对象存储提供静态与媒体文件；Django 仅在 DEBUG 模式下提供
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cache configuration: prefer Redis if configured, else fallback to locmem
REDIS_URL = os.getenv('REDIS_URL', '')
USE_REDIS_CACHE = os.getenv('USE_REDIS_CACHE', 'false').lower() in ('true','1','yes') or bool(REDIS_URL)
if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL or f"redis://{os.getenv('REDIS_HOST','127.0.0.1')}:{os.getenv('REDIS_PORT','6379')}/{os.getenv('REDIS_DB','0')}",
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                'PASSWORD': os.getenv('REDIS_PASSWORD', '') or None,
                'CONNECTION_POOL_KWARGS': {'max_connections': int(os.getenv('REDIS_MAX_CONNECTIONS','50'))},
            },
            'KEY_PREFIX': os.getenv('CACHE_KEY_PREFIX', 'bs01'),
            'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT','60')),
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'default-locmem',
            'TIMEOUT': int(os.getenv('CACHE_DEFAULT_TIMEOUT','60')),
        }
    }

# 模型主键默认类型（避免小整型溢出）
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@example.com')
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')
# SMTP 相关配置（当 EMAIL_BACKEND 使用 SMTP 时生效）
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'false').lower() in ('true', '1', 'yes')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in ('true', '1', 'yes')
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))
EMAIL_SUBJECT_PREFIX = os.getenv('EMAIL_SUBJECT_PREFIX', '')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)
FRONTEND_URL = os.getenv('FRONTEND_URL', '')
PASSWORD_RESET_FRONTEND_PATH = os.getenv('PASSWORD_RESET_FRONTEND_PATH', '/#/reset-password')

def _csv_env(name, default=''):
    v = os.getenv(name, default)
    return [x.strip() for x in v.split(',') if x.strip()]

RESERVED_USERNAMES = _csv_env('RESERVED_USERNAMES', 'admin,root,system,api,auth,login,logout,signup,register,me')
EMAIL_DOMAIN_BLACKLIST = _csv_env('EMAIL_DOMAIN_BLACKLIST', '')
REGISTRATION_REQUIRE_CAPTCHA = os.getenv('REGISTRATION_REQUIRE_CAPTCHA', 'false').lower() in ('true','1','yes')
AVATAR_MAX_SIZE_BYTES = int(os.getenv('AVATAR_MAX_SIZE_BYTES', '2097152'))
EMAIL_VERIFY_TOKEN_MAX_AGE = int(os.getenv('EMAIL_VERIFY_TOKEN_MAX_AGE', '86400'))  # 24h
PASSWORD_RESET_TOKEN_MAX_AGE = int(os.getenv('PASSWORD_RESET_TOKEN_MAX_AGE', '3600'))  # 1h
EMAIL_CHECK_MX = os.getenv('EMAIL_CHECK_MX', 'false').lower() in ('true','1','yes')
DISPOSABLE_DOMAINS = _csv_env('DISPOSABLE_DOMAINS', 'mailinator.com,discard.email,tempmail.com,10minutemail.com')
ADMIN_EMAIL_LIST = _csv_env('ADMIN_EMAIL_LIST', '')
AVATAR_MAX_PIXELS = int(os.getenv('AVATAR_MAX_PIXELS', '25000000'))  # 25MP 默认像素上限

# 让 Django 内置密码重置令牌使用相同过期配置
PASSWORD_RESET_TIMEOUT = PASSWORD_RESET_TOKEN_MAX_AGE

# 登录验证码风控配置（可在 .env 中覆盖）
LOGIN_CODE_MIN_INTERVAL_SECONDS = int(os.getenv('LOGIN_CODE_MIN_INTERVAL_SECONDS', '60'))
LOGIN_CODE_DAILY_LIMIT_EMAIL = int(os.getenv('LOGIN_CODE_DAILY_LIMIT_EMAIL', '20'))
LOGIN_CODE_DAILY_LIMIT_IP = int(os.getenv('LOGIN_CODE_DAILY_LIMIT_IP', '200'))

# 账号密码登录失败风控配置（可在 .env 中覆盖）
LOGIN_PASSWORD_FAIL_WINDOW_SECONDS = int(os.getenv('LOGIN_PASSWORD_FAIL_WINDOW_SECONDS', '600'))
LOGIN_PASSWORD_FAIL_MAX_TRIES_USERNAME = int(os.getenv('LOGIN_PASSWORD_FAIL_MAX_TRIES_USERNAME', '5'))
LOGIN_PASSWORD_FAIL_MAX_TRIES_IP = int(os.getenv('LOGIN_PASSWORD_FAIL_MAX_TRIES_IP', '50'))
LOGIN_PASSWORD_FAIL_COOLDOWN_SECONDS = int(os.getenv('LOGIN_PASSWORD_FAIL_COOLDOWN_SECONDS', '300'))

# 验证码登录失败风控配置（可在 .env 中覆盖）
LOGIN_CODE_LOGIN_FAIL_WINDOW_SECONDS = int(os.getenv('LOGIN_CODE_LOGIN_FAIL_WINDOW_SECONDS', '600'))
LOGIN_CODE_LOGIN_FAIL_MAX_TRIES_EMAIL = int(os.getenv('LOGIN_CODE_LOGIN_FAIL_MAX_TRIES_EMAIL', '5'))
LOGIN_CODE_LOGIN_FAIL_MAX_TRIES_IP = int(os.getenv('LOGIN_CODE_LOGIN_FAIL_MAX_TRIES_IP', '50'))
LOGIN_CODE_LOGIN_FAIL_COOLDOWN_SECONDS = int(os.getenv('LOGIN_CODE_LOGIN_FAIL_COOLDOWN_SECONDS', '300'))

# 视频上传大小限制
VIDEO_MAX_SIZE_BYTES = int(os.getenv('VIDEO_MAX_SIZE_BYTES', '524288000'))  # 500MB 默认

CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', os.getenv('REDIS_URL', 'redis://127.0.0.1:6379/0'))
CELERY_TASK_ALWAYS_EAGER = os.getenv('CELERY_TASK_ALWAYS_EAGER', 'false').lower() in ('true','1','yes')
CELERY_TASK_TIME_LIMIT = int(os.getenv('CELERY_TASK_TIME_LIMIT', '3600'))           # 硬超时 60min
CELERY_TASK_SOFT_TIME_LIMIT = int(os.getenv('CELERY_TASK_SOFT_TIME_LIMIT', '3300')) # 软超时 55min
# 转码任务单独队列，避免阻塞默认队列
CELERY_TASK_DEFAULT_QUEUE = 'default'
CELERY_TASK_QUEUES = (
    Queue('default', routing_key='default.#'),
    Queue('transcode', routing_key='transcode.#'),
)
CELERY_TASK_ROUTES = {
    'tasks.transcode_video_to_hls': {'queue': 'transcode', 'routing_key': 'transcode.hls'},
}

if (not DEBUG) and (not os.getenv('CORS_ALLOWED_ORIGINS')):
    CORS_ALLOWED_ORIGINS = []
    CORS_ALLOW_CREDENTIALS = False

if not DEBUG:
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'true').lower() in ('true','1','yes')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    if os.getenv('USE_X_FORWARDED_PROTO', 'true').lower() in ('true','1','yes'):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# 解决在非 HTTPS 环境下 Redoc/Swagger 的 COOP 报错问题
SECURE_CROSS_ORIGIN_OPENER_POLICY = None
