# Generated by Django 6.0.1 on 2026-01-18 01:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.comment')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video')),
            ],
            options={
                'db_table': 'interactions_comment',
                'managed': True,
                'indexes': [models.Index(fields=['video', '-created_at'], name='idx_comment_video_created')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='videos.video')),
            ],
            options={
                'db_table': 'interactions_favorite',
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='idx_favorite_user'), models.Index(fields=['video'], name='idx_favorite_video')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followed', models.ForeignKey(db_column='followed_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user')),
                ('follower', models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user')),
            ],
            options={
                'db_table': 'interactions_follow',
                'managed': True,
                'indexes': [models.Index(fields=['follower'], name='idx_follow_follower'), models.Index(fields=['followed'], name='idx_follow_followed')],
                'constraints': [models.CheckConstraint(condition=models.Q(('follower', models.F('followed')), _negated=True), name='chk_not_self_follow')],
                'unique_together': {('follower', 'followed')},
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('watch_duration', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='users.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='videos.video')),
            ],
            options={
                'db_table': 'interactions_history',
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='idx_history_user'), models.Index(fields=['video'], name='idx_history_video')],
                'constraints': [models.CheckConstraint(condition=models.Q(('progress__gte', 0), ('progress__lte', 1)), name='chk_history_progress')],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video')),
            ],
            options={
                'db_table': 'interactions_like',
                'managed': True,
                'indexes': [models.Index(fields=['user'], name='idx_like_user'), models.Index(fields=['video'], name='idx_like_video')],
                'unique_together': {('user', 'video')},
            },
        ),
    ]
