# Generated by Cascade: add updated_at trigger on interactions_comment
from django.db import migrations

SQL_FORWARD = r'''
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_comment_updated_at ON interactions_comment;
CREATE TRIGGER trg_comment_updated_at BEFORE UPDATE ON interactions_comment
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
'''

SQL_REVERSE = r'''
DROP TRIGGER IF EXISTS trg_comment_updated_at ON interactions_comment;
'''

class Migration(migrations.Migration):
    dependencies = [
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]
