# Generated by Django 6.0.1 on 2026-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0002_comment_updated_at_trigger'),
        ('users', '0001_initial'),
        ('videos', '0004_playlistvideo_chk_plv_position_nonneg_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='history',
            constraint=models.CheckConstraint(condition=models.Q(('watch_duration__gte', 0)), name='chk_history_watch_duration_nonneg'),
        ),
    ]
