# Generated by Django 6.0.1 on 2026-01-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0003_history_chk_history_watch_duration_nonneg'),
        ('users', '0002_user_birth_date_user_followers_count_and_more'),
        ('videos', '0005_playlistvideo_idx_plv_pos_created'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='idx_comment_user'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent'], name='idx_comment_parent'),
        ),
    ]
