# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0004_comment_idx_comment_user_comment_idx_comment_parent'),
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
        ('videos', '0005_playlistvideo_idx_plv_pos_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'managed': True, 'verbose_name': '评论', 'verbose_name_plural': '评论'},
        ),
        migrations.AlterModelOptions(
            name='favorite',
            options={'managed': True, 'verbose_name': '收藏', 'verbose_name_plural': '收藏'},
        ),
        migrations.AlterModelOptions(
            name='follow',
            options={'managed': True, 'verbose_name': '关注', 'verbose_name_plural': '关注'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'managed': True, 'verbose_name': '观看历史', 'verbose_name_plural': '观看历史'},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'managed': True, 'verbose_name': '点赞', 'verbose_name_plural': '点赞'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='评论ID'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='interactions.comment', verbose_name='父评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.user', verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='收藏ID'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='关注时间'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed',
            field=models.ForeignKey(db_column='followed_id', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.user', verbose_name='被关注者'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(db_column='follower_id', on_delete=django.db.models.deletion.CASCADE, related_name='following', to='users.user', verbose_name='关注者'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='关注ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='历史ID'),
        ),
        migrations.AlterField(
            model_name='history',
            name='progress',
            field=models.FloatField(default=0, verbose_name='播放进度'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='history',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='history',
            name='watch_duration',
            field=models.IntegerField(default=0, verbose_name='观看时长(秒)'),
        ),
        migrations.AlterField(
            model_name='like',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='点赞ID'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video', verbose_name='视频'),
        ),
    ]
