# Generated by Django 6.0.1 on 2026-01-23 09:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0006_follow_idx_follow_follower_created_and_more'),
        ('videos', '0007_video_thumbnail_f_video_video_file_f'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='通知ID')),
                ('verb', models.CharField(max_length=30, verbose_name='类型')),
                ('read', models.BooleanField(default=False, verbose_name='已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='触发者')),
                ('comment', models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='interactions.comment', verbose_name='评论')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='interact_notifications', related_query_name='interact_notification', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('video', models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='videos.video', verbose_name='视频')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'interactions_notification',
                'managed': True,
                'indexes': [models.Index(fields=['user', 'read', '-created_at'], name='idx_notif_user_read_created')],
            },
        ),
    ]
