# Generated by Django 6.0.1 on 2026-01-23 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0007_notification'),
        ('videos', '0007_video_thumbnail_f_video_video_file_f'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='idx_notif_user_read_created',
        ),
        migrations.AddField(
            model_name='notification',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='已隐藏'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'hidden', 'read', '-created_at'], name='ix_nf_uhrc'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'hidden', '-created_at'], name='ix_nf_uhc'),
        ),
    ]
