# Generated by Django 6.0.1 on 2026-01-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0008_remove_notification_idx_notif_user_read_created_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='interaction_user_id_249498_idx',
            old_name='ix_nf_uhrc',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='interaction_user_id_58a6b9_idx',
            old_name='ix_nf_uhc',
        ),
    ]
