# Generated by Django 6.0.1 on 2026-02-14 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactions', '0009_rename_ix_nf_uhrc_interaction_user_id_249498_idx_and_more'),
        ('videos', '0011_video_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'video')},
        ),
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(blank=True, db_column='comment_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='interactions.comment', verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='like',
            name='video',
            field=models.ForeignKey(blank=True, db_column='video_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'comment'), ('user', 'video')},
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['comment'], name='idx_like_comment'),
        ),
    ]
