# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': True, 'verbose_name': '审计日志', 'verbose_name_plural': '审计日志'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': True, 'verbose_name': '视频分类', 'verbose_name_plural': '视频分类'},
        ),
        migrations.AlterModelOptions(
            name='moderationaction',
            options={'managed': True, 'verbose_name': '审核动作', 'verbose_name_plural': '审核动作'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'managed': True, 'verbose_name': '举报', 'verbose_name_plural': '举报'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': True, 'verbose_name': '视频标签', 'verbose_name_plural': '视频标签'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='users.user', verbose_name='操作者'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='日志ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='meta',
            field=models.JSONField(blank=True, null=True, verbose_name='元数据'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='目标ID'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='verb',
            field=models.CharField(max_length=100, verbose_name='操作类型'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='分类ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='action',
            field=models.CharField(max_length=50, verbose_name='动作类型'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='动作ID'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='moderator',
            field=models.ForeignKey(db_column='moderator_id', on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='users.user', verbose_name='审核人'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='原因'),
        ),
        migrations.AlterField(
            model_name='moderationaction',
            name='report',
            field=models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='content.report', verbose_name='对应举报'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='report',
            name='handled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理时间'),
        ),
        migrations.AlterField(
            model_name='report',
            name='handled_by',
            field=models.ForeignKey(blank=True, db_column='handled_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to='users.user', verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='举报ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='moderator_notes',
            field=models.TextField(blank=True, null=True, verbose_name='审核备注'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason_code',
            field=models.CharField(max_length=50, verbose_name='举报原因'),
        ),
        migrations.AlterField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(db_column='reporter_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='users.user', verbose_name='举报人'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_id',
            field=models.UUIDField(verbose_name='目标ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='target_type',
            field=models.CharField(max_length=50, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='标签ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='标签名称'),
        ),
    ]
