# Generated by Django 6.0.1 on 2026-01-18 01:34

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.user')),
            ],
            options={
                'db_table': 'playlists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.CharField(max_length=100)),
                ('thumbnail', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('file_size', models.BigIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('upload_status', models.CharField(default='pending', max_length=20)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.category')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.user')),
            ],
            options={
                'db_table': 'videos_video',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PlaylistVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='videos.playlist')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='videos.video')),
            ],
            options={
                'db_table': 'playlist_videos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.video')),
            ],
            options={
                'db_table': 'videos_asset',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoSubtitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=16)),
                ('format', models.CharField(max_length=16)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ready', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='videos.video')),
            ],
            options={
                'db_table': 'videos_subtitle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_videos', to='content.tag')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='videos.video')),
            ],
            options={
                'db_table': 'videos_video_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VideoTranscode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('bitrate', models.IntegerField(blank=True, null=True)),
                ('codec', models.CharField(blank=True, max_length=50, null=True)),
                ('segment_duration', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='transcodes', to='videos.video')),
            ],
            options={
                'db_table': 'videos_transcode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_later', to='users.user')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_later_users', to='videos.video')),
            ],
            options={
                'db_table': 'watch_later',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['user'], name='idx_playlists_user'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.CheckConstraint(condition=models.Q(('visibility__in', ['public', 'unlisted', 'private'])), name='chk_playlist_visibility'),
        ),
        # Ensure required PostgreSQL extensions (must have proper DB permissions)
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS unaccent;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(condition=models.Q(('status', 'published')), fields=['-published_at'], name='idx_videos_published'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='idx_videos_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='video',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='idx_videos_desc_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'processing', 'published', 'banned'])), name='chk_video_status'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(('upload_status__in', ['pending', 'uploading', 'completed', 'failed'])), name='chk_upload_status'),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 0), ('width__gte', 0), ('height__gte', 0), ('file_size__gte', 0)), name='chk_video_nonnegatives'),
        ),
        migrations.AddIndex(
            model_name='playlistvideo',
            index=models.Index(fields=['playlist', 'position'], name='idx_plv_pos'),
        ),
        migrations.AlterUniqueTogether(
            name='playlistvideo',
            unique_together={('playlist', 'video')},
        ),
        migrations.AddIndex(
            model_name='videoasset',
            index=models.Index(fields=['video'], name='idx_asset_video'),
        ),
        migrations.AddConstraint(
            model_name='videoasset',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['thumbnail', 'sprite', 'gif', 'cover', 'watermark'])), name='chk_asset_kind'),
        ),
        migrations.AddIndex(
            model_name='videosubtitle',
            index=models.Index(fields=['video'], name='idx_subtitle_video'),
        ),
        migrations.AddConstraint(
            model_name='videosubtitle',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'ready', 'failed'])), name='chk_subtitle_status'),
        ),
        migrations.AlterUniqueTogether(
            name='videosubtitle',
            unique_together={('video', 'lang', 'format')},
        ),
        migrations.AddIndex(
            model_name='videotag',
            index=models.Index(fields=['tag', 'video'], name='idx_video_tags_tag_video'),
        ),
        migrations.AlterUniqueTogether(
            name='videotag',
            unique_together={('video', 'tag')},
        ),
        migrations.AddIndex(
            model_name='videotranscode',
            index=models.Index(fields=['video'], name='idx_transcode_video'),
        ),
        migrations.AddIndex(
            model_name='videotranscode',
            index=models.Index(condition=models.Q(('status__in', ['processing', 'pending'])), fields=['status'], name='idx_transcode_status'),
        ),
        migrations.AddConstraint(
            model_name='videotranscode',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'processing', 'ready', 'failed'])), name='chk_transcode_status'),
        ),
        migrations.AlterUniqueTogether(
            name='videotranscode',
            unique_together={('video', 'profile')},
        ),
        migrations.AddIndex(
            model_name='watchlater',
            index=models.Index(fields=['user'], name='idx_watch_later_user'),
        ),
        migrations.AddIndex(
            model_name='watchlater',
            index=models.Index(fields=['video'], name='idx_watch_later_video'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlater',
            unique_together={('user', 'video')},
        ),
    ]
