# Generated by Cascade: add TSV columns, GIN indexes, and triggers (no IMMUTABLE funcs in indexes)
from django.db import migrations

SQL_FORWARD = r'''
-- Ensure unaccent is available (idempotent)
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Add TSV columns
ALTER TABLE videos_video ADD COLUMN IF NOT EXISTS search_tsv tsvector;
ALTER TABLE videos_subtitle ADD COLUMN IF NOT EXISTS tsv tsvector;

-- GIN indexes on TSV columns
CREATE INDEX IF NOT EXISTS idx_videos_search_tsv ON videos_video USING gin (search_tsv);
CREATE INDEX IF NOT EXISTS idx_subtitle_tsv ON videos_subtitle USING gin (tsv);

-- Triggers to maintain TSV columns
CREATE OR REPLACE FUNCTION videos_video_tsv_trigger() RETURNS trigger AS $$
BEGIN
  NEW.search_tsv :=
    setweight(to_tsvector('simple', coalesce(unaccent(NEW.title),'')), 'A') ||
    setweight(to_tsvector('simple', coalesce(unaccent(NEW.description),'')), 'B');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_videos_video_tsv ON videos_video;
CREATE TRIGGER trg_videos_video_tsv BEFORE INSERT OR UPDATE OF title, description ON videos_video
FOR EACH ROW EXECUTE FUNCTION videos_video_tsv_trigger();

CREATE OR REPLACE FUNCTION videos_subtitle_tsv_trigger() RETURNS trigger AS $$
BEGIN
  NEW.tsv := to_tsvector('simple', coalesce(unaccent(NEW.text_content),''));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_videos_subtitle_tsv ON videos_subtitle;
CREATE TRIGGER trg_videos_subtitle_tsv BEFORE INSERT OR UPDATE OF text_content ON videos_subtitle
FOR EACH ROW EXECUTE FUNCTION videos_subtitle_tsv_trigger();

-- Backfill existing rows (idempotent with WHERE ... IS NULL)
UPDATE videos_video
SET search_tsv =
  setweight(to_tsvector('simple', coalesce(unaccent(title),'')), 'A') ||
  setweight(to_tsvector('simple', coalesce(unaccent(description),'')), 'B')
WHERE search_tsv IS NULL;

UPDATE videos_subtitle
SET tsv = to_tsvector('simple', coalesce(unaccent(text_content),''))
WHERE tsv IS NULL;
'''

SQL_REVERSE = r'''
DROP TRIGGER IF EXISTS trg_videos_subtitle_tsv ON videos_subtitle;
DROP FUNCTION IF EXISTS videos_subtitle_tsv_trigger();
DROP TRIGGER IF EXISTS trg_videos_video_tsv ON videos_video;
DROP FUNCTION IF EXISTS videos_video_tsv_trigger();
DROP INDEX IF EXISTS idx_subtitle_tsv;
DROP INDEX IF EXISTS idx_videos_search_tsv;
ALTER TABLE videos_subtitle DROP COLUMN IF EXISTS tsv;
ALTER TABLE videos_video DROP COLUMN IF EXISTS search_tsv;
'''


class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]
