# Generated by Cascade: set_updated_at() and trigger on videos_video
from django.db import migrations

SQL_FORWARD = r'''
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_videos_video_updated_at ON videos_video;
CREATE TRIGGER trg_videos_video_updated_at BEFORE UPDATE ON videos_video
FOR EACH ROW EXECUTE FUNCTION set_updated_at();
'''

SQL_REVERSE = r'''
DROP TRIGGER IF EXISTS trg_videos_video_updated_at ON videos_video;
-- keep set_updated_at() as it may be used by other triggers
'''

class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0002_search_tsv'),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]
