# Generated by Django 6.0.1 on 2026-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_updated_at_trigger'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistvideo',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 0)), name='chk_plv_position_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='videotranscode',
            constraint=models.CheckConstraint(condition=models.Q(('segment_duration__gt', 0)), name='chk_transcode_segment_positive'),
        ),
    ]
