# Generated by Django 6.0.1 on 2026-01-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_playlistvideo_chk_plv_position_nonneg_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlistvideo',
            index=models.Index(fields=['playlist', 'position', 'created_at'], name='idx_plv_pos_created'),
        ),
    ]
