# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_auditlog_options_alter_category_options_and_more'),
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
        ('videos', '0005_playlistvideo_idx_plv_pos_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': True, 'verbose_name': '播放列表', 'verbose_name_plural': '播放列表'},
        ),
        migrations.AlterModelOptions(
            name='playlistvideo',
            options={'managed': True, 'verbose_name': '播放列表视频', 'verbose_name_plural': '播放列表视频'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'managed': True, 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.AlterModelOptions(
            name='videoasset',
            options={'managed': True, 'verbose_name': '视频资源', 'verbose_name_plural': '视频资源'},
        ),
        migrations.AlterModelOptions(
            name='videosubtitle',
            options={'managed': True, 'verbose_name': '视频字幕', 'verbose_name_plural': '视频字幕'},
        ),
        migrations.AlterModelOptions(
            name='videotag',
            options={'managed': True, 'verbose_name': '视频标签关联', 'verbose_name_plural': '视频标签关联'},
        ),
        migrations.AlterModelOptions(
            name='videotranscode',
            options={'managed': True, 'verbose_name': '视频转码记录', 'verbose_name_plural': '视频转码记录'},
        ),
        migrations.AlterModelOptions(
            name='watchlater',
            options={'managed': True, 'verbose_name': '稍后看', 'verbose_name_plural': '稍后看'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=255, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='visibility',
            field=models.CharField(default='public', max_length=20, verbose_name='可见性'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='playlist',
            field=models.ForeignKey(db_column='playlist_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='videos.playlist', verbose_name='播放列表'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='position',
            field=models.IntegerField(default=0, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment_count',
            field=models.BigIntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.IntegerField(default=0, verbose_name='时长(秒)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='文件大小(字节)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='height',
            field=models.IntegerField(default=0, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.BigIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='video',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_status',
            field=models.CharField(default='pending', max_length=20, verbose_name='上传状态'),
        ),
        migrations.AlterField(
            model_name='video',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.CharField(max_length=100, verbose_name='视频文件'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AlterField(
            model_name='video',
            name='width',
            field=models.IntegerField(default=0, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='kind',
            field=models.CharField(max_length=20, verbose_name='资源类型'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='url',
            field=models.TextField(verbose_name='资源URL'),
        ),
        migrations.AlterField(
            model_name='videoasset',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='format',
            field=models.CharField(max_length=16, verbose_name='格式'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='lang',
            field=models.CharField(max_length=16, verbose_name='语言'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='status',
            field=models.CharField(default='ready', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='text_content',
            field=models.TextField(blank=True, null=True, verbose_name='字幕文本'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='字幕URL'),
        ),
        migrations.AlterField(
            model_name='videosubtitle',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, related_name='tag_videos', to='content.tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='videotag',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='video_tags', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True, verbose_name='比特率'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='codec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='编码格式'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='高度'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='profile',
            field=models.CharField(max_length=50, verbose_name='转码规格'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='segment_duration',
            field=models.IntegerField(default=6, verbose_name='分片时长(秒)'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='url',
            field=models.TextField(verbose_name='转码文件URL'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='transcodes', to='videos.video', verbose_name='视频'),
        ),
        migrations.AlterField(
            model_name='videotranscode',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='宽度'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_later', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='video',
            field=models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='watch_later_users', to='videos.video', verbose_name='视频'),
        ),
    ]
