# Generated by Django 6.0.1 on 2026-01-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_alter_playlist_options_alter_playlistvideo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_f',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='videos/thumbs/', verbose_name='缩略图(ImageField)'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file_f',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to='videos/', verbose_name='视频文件(FileField)'),
        ),
    ]
