# Generated by Django 6.0.1 on 2026-01-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='low_mp4',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='低清 MP4 地址'),
        ),
        migrations.AddField(
            model_name='video',
            name='transcode_error',
            field=models.TextField(blank=True, null=True, verbose_name='转码错误信息'),
        ),
    ]
