# Generated by Django 6.0.1 on 2026-01-18 02:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigNamespace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'configs_namespace',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfigKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('value_type', models.CharField(choices=[('string', 'string'), ('int', 'int'), ('bool', 'bool'), ('json', 'json')], default='json', max_length=16)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='configs.confignamespace')),
            ],
            options={
                'db_table': 'configs_key',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfigEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(blank=True, max_length=64, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='configs.configkey')),
            ],
            options={
                'db_table': 'configs_entry',
                'managed': True,
                'indexes': [models.Index(fields=['key'], name='idx_cfg_entry_key'), models.Index(fields=['key', 'content_type', 'object_id'], name='idx_cfg_entry_scope'), models.Index(fields=['-updated_at'], name='idx_cfg_entry_updated')],
                'unique_together': {('key', 'content_type', 'object_id')},
            },
        ),
        migrations.AddIndex(
            model_name='configkey',
            index=models.Index(fields=['namespace', 'key'], name='idx_cfg_key_ns_key'),
        ),
        migrations.AlterUniqueTogether(
            name='configkey',
            unique_together={('namespace', 'key')},
        ),
    ]
