# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configentry',
            options={'managed': True, 'verbose_name': '配置条目', 'verbose_name_plural': '配置条目'},
        ),
        migrations.AlterModelOptions(
            name='configkey',
            options={'managed': True, 'verbose_name': '配置键', 'verbose_name_plural': '配置键'},
        ),
        migrations.AlterModelOptions(
            name='confignamespace',
            options={'managed': True, 'verbose_name': '配置命名空间', 'verbose_name_plural': '配置命名空间'},
        ),
        migrations.AlterField(
            model_name='configentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='关联模型'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='配置条目ID'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='configs.configkey', verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='object_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='configentry',
            name='value',
            field=models.JSONField(blank=True, null=True, verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='default_value',
            field=models.JSONField(blank=True, null=True, verbose_name='默认值'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='配置键ID'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='key',
            field=models.CharField(max_length=64, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='namespace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='configs.confignamespace', verbose_name='命名空间'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='configkey',
            name='value_type',
            field=models.CharField(choices=[('string', 'string'), ('int', 'int'), ('bool', 'bool'), ('json', 'json')], default='json', max_length=16, verbose_name='值类型'),
        ),
        migrations.AlterField(
            model_name='confignamespace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='confignamespace',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='confignamespace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='命名空间ID'),
        ),
        migrations.AlterField(
            model_name='confignamespace',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='命名空间名称'),
        ),
    ]
