# Generated by Django 6.0.1 on 2026-01-18 03:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birth_date_user_followers_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='followers_count',
            field=models.PositiveIntegerField(default=0, verbose_name='粉丝数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='following_count',
            field=models.PositiveIntegerField(default=0, verbose_name='关注数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其他'), ('private', '保密')], default='private', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='是否创作者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='是否员工'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否认证用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后登录'),
        ),
        migrations.AlterField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码哈希'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='privacy_mode',
            field=models.CharField(choices=[('public', '公开'), ('private', '私密'), ('friends_only', '仅好友可见')], default='public', max_length=20, verbose_name='隐私模式'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_likes_received',
            field=models.PositiveIntegerField(default=0, verbose_name='获赞总数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_views_received',
            field=models.PositiveBigIntegerField(default=0, verbose_name='总播放量'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.RegexValidator(message='用户名只能包含字母、数字、下划线和点号', regex='^[a-zA-Z0-9_.]+$')], verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='video_count',
            field=models.PositiveIntegerField(default=0, verbose_name='视频数'),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='个人网站'),
        ),
        migrations.CreateModel(
            name='UserStatistic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='统计ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('new_followers', models.PositiveIntegerField(default=0, verbose_name='新增粉丝')),
                ('new_following', models.PositiveIntegerField(default=0, verbose_name='新增关注')),
                ('likes_received', models.PositiveIntegerField(default=0, verbose_name='收到点赞')),
                ('comments_received', models.PositiveIntegerField(default=0, verbose_name='收到评论')),
                ('shares_received', models.PositiveIntegerField(default=0, verbose_name='收到分享')),
                ('videos_uploaded', models.PositiveIntegerField(default=0, verbose_name='上传视频')),
                ('total_views', models.PositiveBigIntegerField(default=0, verbose_name='总播放量')),
                ('watch_time', models.PositiveBigIntegerField(default=0, verbose_name='总观看时长(秒)')),
                ('login_count', models.PositiveIntegerField(default=0, verbose_name='登录次数')),
                ('active_days', models.PositiveIntegerField(default=0, verbose_name='活跃天数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户统计数据',
                'verbose_name_plural': '用户统计数据',
                'db_table': 'users_user_statistic',
                'indexes': [models.Index(fields=['user', 'date'], name='users_user__user_id_bfded9_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date_stat')],
            },
        ),
    ]
