# Generated by Django 6.0.1 on 2026-01-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_groups_user_is_superuser_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture_f',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='avatars/', verbose_name='头像(ImageField)'),
        ),
    ]
