# Generated by Django 6.0.1 on 2026-04-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_username_nickname_trgm'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_role',
            field=models.CharField(choices=[('none', '无权限'), ('reviewer', '审核员'), ('moderator', '版主'), ('admin', '管理员'), ('super_admin', '超级管理员')], default='none', max_length=20, verbose_name='管理员角色'),
        ),
    ]
