# Generated by Cascade: materialized view mv_video_stats and refresh trigger
from django.db import migrations

SQL_FORWARD = r'''
-- create materialized view with drop-if-exists safeguard
DROP MATERIALIZED VIEW IF EXISTS mv_video_stats;
CREATE MATERIALIZED VIEW mv_video_stats AS
SELECT 
  v.id as video_id,
  v.view_count,
  v.like_count,
  v.comment_count,
  COUNT(DISTINCT l.user_id) as unique_likes,
  COUNT(DISTINCT c.user_id) as unique_comments,
  COALESCE(AVG(h.progress), 0) as avg_completion_rate
FROM videos_video v
LEFT JOIN interactions_like l ON v.id = l.video_id
LEFT JOIN interactions_comment c ON v.id = c.video_id
LEFT JOIN interactions_history h ON v.id = h.video_id
WHERE v.status = 'published'
GROUP BY v.id;

CREATE UNIQUE INDEX IF NOT EXISTS idx_mv_video_stats_video ON mv_video_stats (video_id);

-- non-concurrent refresh function (trigger-safe)
CREATE OR REPLACE FUNCTION refresh_video_stats()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  REFRESH MATERIALIZED VIEW mv_video_stats;
  RETURN NULL;
END;
$$;

-- attach trigger on videos table (statement-level)
DROP TRIGGER IF EXISTS trg_refresh_stats ON videos_video;
CREATE TRIGGER trg_refresh_stats 
  AFTER INSERT OR UPDATE OR DELETE ON videos_video
  FOR EACH STATEMENT EXECUTE FUNCTION refresh_video_stats();
'''

SQL_REVERSE = r'''
DROP TRIGGER IF EXISTS trg_refresh_stats ON videos_video;
DROP FUNCTION IF EXISTS refresh_video_stats();
DROP MATERIALIZED VIEW IF EXISTS mv_video_stats;
'''

class Migration(migrations.Migration):
    dependencies = [
        ('videos', '0001_initial'),
        ('interactions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(sql=SQL_FORWARD, reverse_sql=SQL_REVERSE),
    ]
