# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_mv_video_stats'),
        ('videos', '0005_playlistvideo_idx_plv_pos_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStats',
            fields=[
                ('video', models.OneToOneField(db_column='video_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='stats', serialize=False, to='videos.video', verbose_name='视频')),
                ('view_count', models.BigIntegerField(verbose_name='播放次数')),
                ('like_count', models.BigIntegerField(verbose_name='点赞数')),
                ('comment_count', models.BigIntegerField(verbose_name='评论数')),
                ('unique_likes', models.BigIntegerField(verbose_name='唯一点赞用户数')),
                ('unique_comments', models.BigIntegerField(verbose_name='唯一评论用户数')),
                ('avg_completion_rate', models.FloatField(verbose_name='平均完播率')),
            ],
            options={
                'verbose_name': '视频统计',
                'verbose_name_plural': '视频统计',
                'db_table': 'mv_video_stats',
                'managed': False,
            },
        ),
    ]
