# Generated by Django 6.0.1 on 2026-01-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__gte', 0)), name='chk_delivery_attempt_nonneg'),
        ),
    ]
