# Generated by Django 6.0.1 on 2026-01-18 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_data_notification_notification_type'),
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fcmdevicetoken',
            options={'managed': True, 'verbose_name': 'FCM 设备令牌', 'verbose_name_plural': 'FCM 设备令牌'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True, 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.AlterModelOptions(
            name='notificationdelivery',
            options={'managed': True, 'verbose_name': '通知投递记录', 'verbose_name_plural': '通知投递记录'},
        ),
        migrations.AlterModelOptions(
            name='webpushsubscription',
            options={'managed': True, 'verbose_name': 'Web 推送订阅', 'verbose_name_plural': 'Web 推送订阅'},
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='platform',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='平台'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='token',
            field=models.TextField(unique=True, verbose_name='设备令牌'),
        ),
        migrations.AlterField(
            model_name='fcmdevicetoken',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to='users.user', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='通知数据'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='generic', max_length=50, verbose_name='通知类型'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(db_column='recipient_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.user', verbose_name='接收者'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='attempt_count',
            field=models.IntegerField(default=0, verbose_name='尝试次数'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(max_length=20, verbose_name='推送渠道'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='错误信息'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后尝试时间'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(db_column='notification_id', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification', verbose_name='通知'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='auth',
            field=models.TextField(blank=True, null=True, verbose_name='认证密钥'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='浏览器'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='device',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='endpoint',
            field=models.TextField(unique=True, verbose_name='推送端点'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后活跃时间'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='p256dh',
            field=models.TextField(blank=True, null=True, verbose_name='P256DH 密钥'),
        ),
        migrations.AlterField(
            model_name='webpushsubscription',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to='users.user', verbose_name='用户'),
        ),
    ]
