# Generated by Django 6.0.1 on 2026-02-15 08:10

import django.db.models.deletion
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_fcmdevicetoken_options_and_more'),
        ('users', '0003_alter_user_options_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否发布')),
                ('pinned', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告',
                'db_table': 'system_announcement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemAnnouncementRead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='已读时间')),
                ('announcement', models.ForeignKey(db_column='announcement_id', on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='notifications.systemannouncement', verbose_name='公告')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='users.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': '系统公告已读',
                'verbose_name_plural': '系统公告已读',
                'db_table': 'system_announcement_read',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['is_active', '-published_at'], name='idx_announce_active_pub'),
        ),
        migrations.AddIndex(
            model_name='systemannouncement',
            index=models.Index(fields=['pinned', '-published_at'], name='idx_announce_pinned_pub'),
        ),
        migrations.AddIndex(
            model_name='systemannouncementread',
            index=models.Index(fields=['user', 'announcement'], name='idx_announce_read_user'),
        ),
        migrations.AddIndex(
            model_name='systemannouncementread',
            index=models.Index(fields=['announcement', 'user'], name='idx_announce_read_ann'),
        ),
        migrations.AddConstraint(
            model_name='systemannouncementread',
            constraint=models.UniqueConstraint(fields=('announcement', 'user'), name='uq_announce_user_read'),
        ),
    ]
